# version: "2"
# services:
#   app:
#     container_name: app
#     restart: always
#     build: .
#     ports:
#             - "8080:8080"
#     depends_on:
#             - mongodb
#   mongodb:
#     image: mongo
#     restart: always
#     container_name: mongodb
#     volumes:
#         - ./data-node:/data/db
#     ports:
#         - 27017:27017
#     command: mongod --noauth --smallfiles
version: "3"
services:
  app:
    container_name: yak-yik
    restart: always
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --noauth --smallfiles
